### ISSUE TITLE
Needs dark mode

### ISSUE THREAD

**Issue by astro-develops** [vExcess/vexcess-academy#1]
Dark code editor + light background hurts my eyes. Add dark mode plz.

**Comment by Zushah** [comment]
Sure thing

**Comment by Zushah** [comment]
lol nevermind I give up

**Comment by vExcess** [comment]
oof, guess I'll have to do it myself when I'm not busy with school. Unless someone else is able to

**Comment by vExcess** [comment]
I dunno that it's the best dark mode theme, but it's good enough I guess.
