### ISSUE TITLE
i cant get in your website under profile ,>>?(nokia input)

### ISSUE THREAD

**Issue by 457fede** [vExcess/vexcess-academy#2]
i try to get in but couldn't ,help

**Comment by vExcess** [comment]
The website is down because I'm trying to properly secure the database. But it's not working and it seems nobody anywhere can tell me why. 
https://stackoverflow.com/questions/77262963/how-to-authenticate-into-mongodb-using-node-js-driver

**Comment by 457fede** [comment]
understood ,hope you good luck

**Comment by vExcess** [comment]
The website is back online
